export class EmployeeMaster {
  ID: any = 0;
  NAME: any = '';
  FIRST_NAME: any = '';
  MIDDLE_NAME: any = '';
  LAST_NAME: any = '';
  EMPLOYEE_CODE: any = 0;
  GRADE_PAY: any;
  OFFICE_NAME: any = '';
  DESIGNATION_ID: any = '';
  GRADE_PAY_LEVEL_ID: any;
  LOCATION: any = '';
  DDO_OF_THE_OFFICIAL: any = '';
  EMAIL_ID: any;
  MOBILE_NO: any;
  BASIC_PAY: any;
  PASSWORD: any = 12345678;
  ADDRESS: any;
  CLAIM_ID: any = 0;
  STATUS: any = true;
  CAST: any;
  SERVICE_TYPE: any = '';
  JOINING_DATE: any;
  DOB: any;
  GRASS_GRADE_PAY: any;
  AGE: any;
  GENDER: any = '';
  CAST_CERTIFICATE: any;
  PROFILE_PHOTO: any;
  IS_EX_SERVICEMAN: any = 0;
  DATE_OF_JOINING_MILITORY: any;
  DATE_OF_RETIREMENT_MILITORY: any;
  RETIREMENT_DATE: any;
  GRAAS_GRADE_PAY_ID: any;
  PRESENT_PAY_LEVEL_DATE: any;
  IS_PRESENT_PAY_LEVEL_CHANGED: any = 0;
  DESIGNATION: any;
  DDO_OF_THE_OFFICIAL_ID: any = '';
}
