export class finalallocationdetailsemp{
    ID:number;
    FINAL_ALLOTMENT_MASTER_ID: number;
    FLAT_ID: number;
    EMP_ID:number;
    ALLOTMENT_DATE_TIME:any;
    STATUS:any;
    REMARK:any;
    TAKEN_STATUS:any;
    ACCEPTANCE_LETTER:any;
    INSPECTOR_STATUS:any;
    INSPECTOR_REMARK:any;
    ACCEPTANCE_LETTER_DATE_TIME:any;
    STEP_NO:any;
    INSPETOR_APPROVE_DATE_TIME:any;
    PRINT_DATE_TIME:any;
    UPLOAD_SUBMITE_DATE_TIME:any;
    IS_ACCEPTANCE_LETTER_SUBMITED:any;
    PRINT_ALLOTMENT_ORDER_DATE_TIME:any;
    PRINT_AUTHORISATION_ORDER_DATE_TIME:any;
    AUTHORISATION_SIGNATURE1:any;
    AUTHORISATION_SIGNATURE2:any;
    ALLOTMENT_FINAL_SIGNATURE:any;
}