export class ChangeFlatCreateMaster {
    ID: any;
CHANGE_STEP_NO:any;
FINAL_FLAT_TAKEN_ID:any;
IS_SUBMITTED:any;
APPLIED_FOR_CHANGE_DATE_TIME:any;
CHANGE_RESIDENCE_TYPE_ID:any;
CHANGE_REASON_TYPE:any;
CHANGE_REASON:any;
CHANGE_INSPECTOR_STATUS:any;
CHANGE_INSPECTOR_REMARK:any;
CHANGE_FORM:any;
CHANGE_PRINT_DATE_TIME:any;
CHANGE_UPLOAD_DATE_TIME:any;
CHANGE_INSPECTOR_APPROVED_DATE_TIME:any;
EMP_ID:any;
}