export class NonAcceptanceMaster {
    ID: any;
    // FINAL_FLAT_TAKEN_ID:any;
    FINAL_FLAT_ALLOTMENT_DETAILS_ID:any;
FLAT_ID:any;
EMP_ID:any;
NON_ACCEPTANCE_FORM:any;
NON_ACCEPTANCE_FORM_SUBMITTED_DATE_TIME:any;
IS_NON_ACCEPTANCE_FORM_SUBMITTED:boolean;
NON_ACCEPTANCE_STEP_NO:any;
NON_ACCEPTANCE_PRINT_DATE_TIME:any;
NON_ACCEPTANCE_INSPECTOR_REMARK:any;
INSPECTOR_ID:any;
NON_ACCEPTANCE_INSPECTOR_APPROVED_DATE_TIME:any;
NON_ACCEPTANCE_INSPECTOR_STATUS:boolean;
CLIENT_ID=1;
NON_ACCEPTANCE_TEXT:any;

}