export class checkListltc1 {
  ID:any;
  LTC_ID: any;
  JOURNEY_DETAILS_ONE: any = 1;
  JOURNEY_DETAILS_TWO: any = 1;
  JOURNEY_DETAILS_THREE: any = 1;
  JOURNEY_DETAILS_FOUR: any = 1;
  JOURNEY_DETAILS_FIVE: any = 1;
  JOURNEY_DETAILS_SIX: any = 1;
  JOURNEY_DETAILS_SEVEN: any = 1;
  JOURNEY_DETAILS_EIGHT: any = 1;
  JOURNEY_DETAILS_FIVE_REMARK1: any = '';
  JOURNEY_DETAILS_FIVE_REMARK2: any = '';
  JOURNEY_DETAILS_FIVE_REMARK3: any = '';
}
