export class MedicalSignatureData {
  ID: any = 0;
  CLAIM_ID: any;
  CLAIM_NEW_ORDER_SIGNATURE_1: any;
  CLAIM_NEW_ORDER_SIGNATURE_2: any;
  CLAIM_ORDER_SIGNATURE_1: any;
  CLAIM_ORDER_SIGNATURE_2: any;
  CLAIM_CLAIM_FILE_SIGNATURE_1: any;
  CLAIM_CLAIM_FILE_SIGNATURE_2: any;
  ADV_CLAIM_NEW_ORDER_SIGNATURE_1: any;
  ADV_CLAIM_NEW_ORDER_SIGNATURE_2: any;
  ADV_CLAIM_ORDER_SIGNATURE_1: any;
  ADV_CLAIM_ORDER_SIGNATURE_2: any;
  ADV_CLAIM_CLAIM_FILE_SIGNATURE_1: any;
  ADV_CLAIM_CLAIM_FILE_SIGNATURE_2: any;
}
